export const eqltyVaultAbi = [
  {
    type: "event",
    name: "TradeExecuted",
    anonymous: false,
    inputs: [
      { name: "strategyId", type: "uint256", indexed: true },
      { name: "nonce", type: "uint256", indexed: true },
      { name: "signalHash", type: "bytes32", indexed: true },
      { name: "quoteHash", type: "bytes32", indexed: false },
      { name: "amountIn", type: "uint256", indexed: false },
      { name: "amountOut", type: "uint256", indexed: false },
      { name: "router", type: "address", indexed: false },
    ],
  },
  {
    type: "function",
    name: "RISK_SIGNER",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "TOKEN_SPENDER",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "executionNonce",
    stateMutability: "view",
    inputs: [{ name: "strategyId", type: "uint256" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "availableBalance",
    stateMutability: "view",
    inputs: [{ name: "strategyId", type: "uint256" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "strategies",
    stateMutability: "view",
    inputs: [{ name: "strategyId", type: "uint256" }],
    outputs: [
      { name: "owner", type: "address" },
      { name: "agent", type: "address" },
      { name: "inputToken", type: "address" },
      { name: "outputToken", type: "address" },
      { name: "router", type: "address" },
      { name: "maxAmountPerTrade", type: "uint128" },
      { name: "maxTotalSpend", type: "uint128" },
      { name: "spent", type: "uint128" },
      { name: "expiresAt", type: "uint64" },
      { name: "maxSlippageBps", type: "uint16" },
      { name: "paused", type: "bool" },
      { name: "revoked", type: "bool" },
      { name: "humanProofHash", type: "bytes32" },
    ],
  },
  {
    type: "function",
    name: "execute",
    stateMutability: "nonpayable",
    inputs: [
      {
        name: "execution",
        type: "tuple",
        components: [
          { name: "strategyId", type: "uint256" },
          { name: "amountIn", type: "uint256" },
          { name: "quotedAmountOut", type: "uint256" },
          { name: "minAmountOut", type: "uint256" },
          { name: "deadline", type: "uint256" },
          { name: "signalHash", type: "bytes32" },
          { name: "quoteHash", type: "bytes32" },
          { name: "calldataHash", type: "bytes32" },
          { name: "nonce", type: "uint256" },
        ],
      },
      { name: "routerCalldata", type: "bytes" },
      { name: "signature", type: "bytes" },
    ],
    outputs: [{ name: "amountOut", type: "uint256" }],
  },
] as const;

export const eqltyExecutionTypes = {
  Execution: [
    { name: "strategyId", type: "uint256" },
    { name: "amountIn", type: "uint256" },
    { name: "quotedAmountOut", type: "uint256" },
    { name: "minAmountOut", type: "uint256" },
    { name: "deadline", type: "uint256" },
    { name: "signalHash", type: "bytes32" },
    { name: "quoteHash", type: "bytes32" },
    { name: "calldataHash", type: "bytes32" },
    { name: "nonce", type: "uint256" },
  ],
} as const;
